# Generated by Django 4.1.1 on 2022-09-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_activity_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
