all:
  children:
    prod:
      children:
        prodserver:
          hosts:
            54.151.104.14:
              ansible_user: root
              ansible_ssh_private_key_file: "~/.ssh/fitness.pem"
              ansible_python_interpreter: /usr/bin/python3
              dev: 'no'
              fitnesssettings: fitness.settings
              # nginx_host_names: recipeas.org
              # csrf_host_name: https://recipeas.org
              acme_challenge_type: http-01
              acme_directory: https://acme-v02.api.letsencrypt.org/directory
              acme_version: 2
              acme_email: michael.humphrey616@gmail.com
              letsencrypt_dir: /etc/letsencrypt
              letsencrypt_keys_dir: /etc/letsencrypt/keys
              letsencrypt_csrs_dir: /etc/letsencrypt/csrs
              letsencrypt_certs_dir: /etc/letsencrypt/certs
              letsencrypt_account_key: /etc/letsencrypt/account/account.key
